import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CartProvider from "@/context/CartProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">


        <header className="px-5 py-2 flex items-center justify-between gap-5 bg-stone-800">

          <Link href="/">
            <img src="/logo.png" alt="" className="w-[120px] py-4 brightness-1000 sepia hue-rotate-[330deg] saturate-[8] rounded-full" />
          </Link>

          <div className="space-x-5">
            <Link href="/foods" className="btn">Foods</Link>
            <Link href="/reviews" className="btn">Reviews</Link>
          </div>

        </header>

        <main className="px-5 py-5">
          
          <CartProvider>{children}</CartProvider>
        </main>
      </body>
    </html>
  );
}
