import React from 'react';
import ReviewsPage from './reviewspage';


export const metadata = {
    title: "Customer Reaction",
    description: "Generated by create next app",
};

const page = () => {


    return (
        <div>
            <ReviewsPage></ReviewsPage>
        </div>
    );
};

export default page;